const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
const source = fs.readFileSync(require.resolve('../game/progression.ts'), 'utf8');
const output = ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.CommonJS } }).outputText;
const target = { exports: {} };
new Function('exports', 'module', output)(target.exports, target);
const { hydrateProgress, applyRunProgress, claimJourney } = target.exports;
let p = hydrateProgress({ tutorialComplete: true });
assert.equal(p.journeyObstacles, 0);
assert.equal(p.firstPurchaseGift, false);
assert.equal(claimJourney(p, 25).reward, 0);
const stats = { obstacles: 25, doubleJumps: 0, bonuses: 0, jaguars: 0, outfitId: 'classic', score: 250 };
p = applyRunProgress(p, stats);
const first = claimJourney(p, 25);
assert.equal(first.reward, 50);
assert.equal(claimJourney(first.progress, 25).reward, 0);
assert.equal(claimJourney(first.progress, 999).reward, 0);
p = hydrateProgress({ ...first.progress, missionDate: '2000-01-01' });
assert.equal(p.journeyObstacles, 25);
assert.deepEqual(p.journeyClaimed, [25]);
p = applyRunProgress(p, { ...stats, obstacles: 5, countRun: false });
assert.equal(p.journeyObstacles, 30);
assert.equal(p.runsCompleted, 1);
assert.equal(p.tutorialComplete, true);
console.log('Journey: migration, thresholds, duplicate claims, date rollover and continue deltas passed');
const { weekKey, claimWeekly, getWeeklyChallenges, claimMastery } = target.exports;
assert.equal(weekKey('2026-09-13'), '2026-09-07');
assert.equal(weekKey('2026-09-14'), '2026-09-14');
assert.equal(weekKey('2027-01-01'), '2026-12-28');
let w = hydrateProgress({ weekStart: '2026-09-07', weekly: { obstacles: 100, runs: 10, bonuses: 12, doubleJumps: 30, jaguars: 0 } }, '2026-09-13');
const weekly = claimWeekly(w, 'weekly-obstacles', '2026-09-07', '2026-09-13');
assert.equal(weekly.reward, 150);
assert.equal(claimWeekly(weekly.progress, 'weekly-obstacles', '2026-09-07', '2026-09-13').reward, 0);
assert.equal(claimWeekly(w, 'weekly-obstacles', '2026-09-07', '2026-09-14').reward, 0);
assert.equal(hydrateProgress(w, '2026-09-14').weekly.obstacles, 0);
assert.equal(getWeeklyChallenges('2026-09-07').length, 3);
assert.notEqual(getWeeklyChallenges('2026-09-07')[2].id, getWeeklyChallenges('2026-09-14')[2].id);
let m = hydrateProgress({ outfitMastery: { classic: 225 }, firstPurchaseGift: true, journeyObstacles: 80 });
assert.equal(claimMastery(m, 'classic', 4).reward, 0);
assert.equal(claimMastery(m, 'unowned', 3).reward, 0);
const reward = claimMastery(m, 'classic', 10);
assert.equal(reward.reward, 150);
assert.equal(claimMastery(reward.progress, 'classic', 10).reward, 0);
assert.equal(reward.progress.firstPurchaseGift, true);
assert.equal(reward.progress.journeyObstacles, 80);
assert.equal(p.weekly.obstacles, 30);
assert.equal(p.weekly.runs, 1);
console.log('Weekly/mastery: rollover, year boundary, rotation, repeat claims, migrations and continue deltas passed');
